# # collect interval
# interval = 15

[[instances]]
targets = [
     "{{.url}}"
]

## HTTP Request Method
method = "{{.method}}"

## Set response_timeout (default 5 seconds)
# response_timeout = "5s"

## Whether to follow redirects from the server (defaults to false)
# follow_redirects = false

## Optional HTTP Basic Auth Credentials
{{if .username}}username = "{{.username}}"{{end}}
{{if .password}}password = "{{.password}}"{{end}}

## Optional headers
# headers = ["Header-Key-1", "Header-Value-1", "Header-Key-2", "Header-Value-2"]

## Optional HTTP Request Body
{{if .body}}body = '''{{.body}}'''{{end}}

## Optional substring match in body of the response (case sensitive)
# expect_response_substring = "ok"

## Optional expected response status code.
# expect_response_status_code = 0

## Optional TLS Config
{{if .use_tls}}use_tls = true{{end}}
# tls_ca = "/etc/categraf/ca.pem"
# tls_cert = "/etc/categraf/cert.pem"
# tls_key = "/etc/categraf/key.pem"
## Use TLS but skip chain & host verification
{{if .use_tls}}insecure_skip_verify = true{{end}}